apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: silly-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: silly-demo
  minReplicaCount: 1
  maxReplicaCount: 20
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.monitoring:80
        threshold: "2000000000"
        query: sum(container_memory_usage_bytes{namespace="a-team", container="silly-demo"})
