apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: silly-demo
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: silly-demo
  updatePolicy:
    updateMode: Auto
