apiVersion: batch/v1
kind: CronJob
metadata:
  name: silly-demo
  labels:
    app.kubernetes.io/name: silly-demo
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: silly-demo
        spec:
          restartPolicy: OnFailure
          containers:
            - image: cgr.dev/chainguard/bash
              name: silly-demo
              command: ["echo", "What is this?"]
