apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: jenkins
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: jenkins
  updatePolicy:
    updateMode: Auto
