---
apiVersion: v1
kind: ConfigMap
metadata:
  name: silly-demo
  labels:
    app.kubernetes.io/name: silly-demo
data:
  videos.yaml: |
    - id: "1"
      title: something
    - id: "2"
      title: else
    - id: "3"
      title: something new
  message: Hello, DevOps Toolkit!
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: silly-demo
  labels:
    app.kubernetes.io/name: silly-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: silly-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: silly-demo
    spec:
      containers:
        - image: ghcr.io/vfarcic/silly-demo:1.4.235-alpine
          name: silly-demo
          ports:
            - containerPort: 8080    
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          envFrom:
            - configMapRef:
                name: silly-demo
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: silly-demo
                  key: message
          volumeMounts:
            - name: cache
              mountPath: /cache
      volumes:
        - name: cache
          configMap:
            name: silly-demo
