---
apiVersion: v1
kind: Secret
metadata:
  name: silly-demo
  labels:
    app.kubernetes.io/name: silly-demo
data:
  videos.yaml: LSBpZDogIjEiCiAgdGl0bGU6IHNvbWV0aGluZwotIGlkOiAiMiIKICB0aXRsZTogZWxzZQotIGlkOiAiMyIKICB0aXRsZTogc29tZXRoaW5nIG5ldwo=
  message: SGVsbG8sIERldk9wcyBUb29sa2l0IQo=
  silly: ZGVtbwo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: silly-demo
  labels:
    app.kubernetes.io/name: silly-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: silly-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: silly-demo
    spec:
      containers:
        - image: ghcr.io/vfarcic/silly-demo:1.4.235-alpine
          name: silly-demo
          ports:
            - containerPort: 8080    
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          volumeMounts:
            - name: cache
              mountPath: /cache
      volumes:
        - name: cache
          secret:
            secretName: silly-demo
