---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: silly-demo
  labels:
    app.kubernetes.io/name: silly-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: silly-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: silly-demo
    spec:
      containers:
        - image: ghcr.io/vfarcic/silly-demo:1.4.116
          name: silly-demo
          ports:
            - containerPort: 8080    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sillier-demo
  labels:
    app.kubernetes.io/name: sillier-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: sillier-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sillier-demo
    spec:
      containers:
        - image: ghcr.io/vfarcic/silly-demo:1.4.116
          name: sillier-demo
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: something-else
  labels:
    app.kubernetes.io/name: something-else
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: something-else
  template:
    metadata:
      labels:
        app.kubernetes.io/name: something-else
    spec:
      containers:
        - image: ghcr.io/vfarcic/silly-demo:1.4.116
          name: something-else
          ports:
            - containerPort: 8080    
